### ISSUE TITLE
An image template not found to use SSH keys.

### ISSUE THREAD

**Issue by einyx** [terraform-providers/terraform-provider-profitbricks#3]
### Terraform Version
Terraform v0.10.0-rc1-dev

### Affected Resource(s)
- profitbricks_server

### Debug Output
Error applying plan:

1 error(s) occurred:

* profitbricks_server.gitlab: 1 error(s) occurred:

* profitbricks_server.gitlab: Error creating server: ({
  "httpStatus" : 422,
  "messages" : [ {
    "errorCode" : "100",
    "message" : "[(root).entities.volumes.items.[0].properties.sshKeys] An image template not found to use SSH keys."
  } ]
}
)

### Expected Behavior
It should have created a server using a snapshot image

### Actual Behavior
Complain about an ssh template?

### Steps to Reproduce
Create a snapshot with packer and then try to use it in terraform

**Comment by jasminSPC** [comment]
@einyx can you please send part of the TF file you used.

**Comment by einyx** [comment]
resource "profitbricks_server" "gitlab" {
  name              = "staging-gitlab"
  datacenter_id     = "e61af51e-3fb1-481f-835c-eefcab0e2432"
  cores             = 1
  ram               = 1024
  availability_zone = "ZONE_1"
  cpu_family        = "AMD_OPTERON"

  volume {
    name           = "xx-xx"
    image_name     = "xxx-xxx-xxx" < (snapshot NAME)
    size           = 20
    disk_type      = "SSD"
    ssh_key_path = ["/home/xxx/.ssh/packer.pub"] 
    licence_type   = "LINUX"
  }

  nic {
    lan             = "xx"
    dhcp            = true
    firewall_active = true

    firewall {
      protocol         = "TCP"
      name             = "SSH"
      port_range_start = 22
      port_range_end   = 22
    }
  }
}

**Comment by jasminSPC** [comment]
@einyx current implementation of the plugin does not support usage of snapshots only images can be used.

**Comment by einyx** [comment]
doc could be amended perhaps meanwhile?

> image_name - [string] The image or snapshot ID. It is required if licence_type is not provided.

**Comment by jasminSPC** [comment]
@einyx it's a obvious mistake. We will see to get it fixed. Meanwhile you can use image UUID or image name (or just part of it). 

Sorry for inconvenience

**Comment by einyx** [comment]
@jasminSPC can you see an eta on this? Just trying to figure out timing to put down some work on top of this plugin

**Comment by jasminSPC** [comment]
@einyx we are working on implementation of the missing feature. In the next few days we will have the solution for this.

**Comment by jasminSPC** [comment]
Fixed with #6

**Comment by einyx** [comment]
I've built from the latest version on here but I still get 

` "[(root).entities.volumes.items.[0].properties.sshKeys] An image template not found to use SSH keys."
:(`

**Comment by einyx** [comment]
@jasmingacic perhaps?

**Comment by jasmingacic** [comment]
if you use password or ssh key with snapshot then you will get this error message

```
* profitbricks_server.gitlab01: Passwords/SSH keys  are not supported for snapshots.
```

**Comment by jasmingacic** [comment]
```
resource "profitbricks_datacenter" "dc"{
name = "dc"
location = "us/las"
}
resource "profitbricks_server" "gitlab" {
  name              = "xxx"
  datacenter_id     = "${profitbricks_datacenter.dc.id}"
  cores             = 1
  ram               = 1024
  availability_zone = "ZONE_1"
  cpu_family        = "AMD_OPTERON"

  volume {
    name         = "xx-xx"
    image_name   = "ubuntu:latest"
    size         = 20
    disk_type    = "SSD"
    ssh_key_path = ["/Users/jasmingacic/.ssh/id_rsa.pub"]
    licence_type = "LINUX"
  }

  nic {
    lan             = 1 
    dhcp            = true
    firewall_active = true

    firewall {
      protocol         = "TCP"
      name             = "SSH"
      port_range_start = 22
      port_range_end   = 22
    }
  }
}

resource "profitbricks_server" "gitlab01" {
  name              = "xxx"
  datacenter_id     = "${profitbricks_datacenter.dc.id}"
  cores             = 1
  ram               = 1024
  availability_zone = "ZONE_1"
  cpu_family        = "AMD_OPTERON"

  volume {
    name         = "xx-xx"
    image_name   = "1446dba1-a4fe-4aba-b440-dc58f6a0845f"
    size         = 20
    disk_type    = "SSD"
  }

  nic {
    lan             = 1
    dhcp            = true
    firewall_active = true

    firewall {
      protocol         = "TCP"
      name             = "SSH"
      port_range_start = 22
      port_range_end   = 22
    }
  }
}
```

The example shows usage of image (gitlab) and snapshot (gitlab01). From experience you are probably passing incorrect path to your SSH key.

**Comment by einyx** [comment]
volume.3852631023.image_name:                        "" => "51964202-f552-4003-8c5c-9a2ee184a7e7"
  volume.3852631023.image_password:                    "" => ""
  volume.3852631023.licence_type:                      "" => "LINUX"
  volume.3852631023.name:                              "" => "staging-gitlab"
  volume.3852631023.size:                              "" => "20"
  volume.3852631023.ssh_key_path.#:                    "0" => "0"
Error applying plan:
Funny enough, I'm using it for gitlab as well but I get
I get the ID of the snapshot from the profitbricks cli but then:

```1 error(s) occurred:
* profitbricks_server.gitlab: 1 error(s) occurred:

* profitbricks_server.gitlab: Error fetching image: {
  "httpStatus" : 404,
  "messages" : [ {
    "errorCode" : "309",
    "message" : "Resource does not exist"
  } ]
}
```

**Comment by jasmingacic** [comment]
Are you sure you have the correct version?

**Comment by einyx** [comment]
I have built from the latest master, and removed the generated plugin bins from previous builds.
I'm not sure where's the issue, terraform is at version 0.10.8

**Comment by jasmingacic** [comment]
@einyx are you using correct snapshot UUID?

**Comment by einyx** [comment]
seems like @jasmingacic

**Comment by einyx** [comment]
any advice on how to debug this further guys?

**Comment by jasmingacic** [comment]
Perhaps you could use TF_LOG=DEBUG to get more information.
